### ISSUE TITLE
ImportError: No module named google.protobuf

### ISSUE THREAD

**Issue by Murukarthick** [kern-lab/diploSHIC#12]
Hi
I am getting error when i was running train mode step. My command as follow, 
python diploSHIC.py train --numSubWins 22 trainingSets/ trainingSets/ bfsModel

and the error, 

Using TensorFlow backend.
Traceback (most recent call last):
  File "/opt/Bio/diploSHIC/20180904/bin/diploSHIC.py", line 120, in <module>
    from keras.models import Sequential, Model
  File "/opt/Bio/diploSHIC/20180904/venv/lib64/python2.7/site-packages/keras/__init__.py", line 3, in <module>
    from . import utils
  File "/opt/Bio/diploSHIC/20180904/venv/lib64/python2.7/site-packages/keras/utils/__init__.py", line 6, in <module>
    from . import conv_utils
  File "/opt/Bio/diploSHIC/20180904/venv/lib64/python2.7/site-packages/keras/utils/conv_utils.py", line 9, in <module>
    from .. import backend as K
  File "/opt/Bio/diploSHIC/20180904/venv/lib64/python2.7/site-packages/keras/backend/__init__.py", line 89, in <module>
    from .tensorflow_backend import *
  File "/opt/Bio/diploSHIC/20180904/venv/lib64/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 5, in <module>
    import tensorflow as tf
  File "/opt/Bio/diploSHIC/20180904/venv/lib64/python2.7/site-packages/tensorflow/__init__.py", line 22, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/opt/Bio/diploSHIC/20180904/venv/lib64/python2.7/site-packages/tensorflow/python/__init__.py", line 52, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/opt/Bio/diploSHIC/20180904/venv/lib64/python2.7/site-packages/tensorflow/core/framework/graph_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
ImportError: No module named google.protobuf

Although protobuf available i am getting No module error. Is it bug or something went wrong ? I would appreciate if you give some suggestions. 

Thanks,
Karthick

**Comment by Murukarthick** [comment]
solved
