### ISSUE TITLE
TypeError: rogers_huff_r() got an unexpected keyword argument 'fill'

### ISSUE THREAD

**Issue by yunusbb** [kern-lab/diploSHIC#19]
I am running the example analysis on mosquito data described here https://github.com/kern-lab/diploSHIC/wiki/A-soup-to-nuts-example
 and got to the point when diploSHIC calculates feature vectors on the real dataset (mosquito data).

so when I try to run the following command:

module load diploSHIC
python3 /storage/software/diploSHIC/diploSHIC/diploSHIC.py fvecVcf diploid exampleApplication/ag1000g.phase1.ar3.pass.biallelic.3R.vcf.28000000-29000000.gz 3R 53200684 exampleApplication/ag1000g.phase1.ar3.pass.biallelic.3R.vcf.28000000-29000000.gz.diploid.fvec --targetPop BFS --sampleToPopFileName exampleApplication/samples_pops.txt --winSize 55000 --maskFileName exampleApplication/Anopheles-gambiae-PEST_CHROMOSOMES_AgamP3.accessible.fa.gz

I am getting this error:

tail slurm-936956.out
...
27990001-27995000 num unmasked snps: 0; unmasked frac: 0.749200
27995001-28000000 num unmasked snps: 0; unmasked frac: 0.645000
28000001-28005000 num unmasked snps: 498; unmasked frac: 0.742600
Traceback (most recent call last):
  File "/storage/software/diploSHIC/diploSHIC/makeFeatureVecsForChrArmFromVcfDiploid.py", line 143, in <module>
    calcAndAppendStatValForScanDiplo(alleleCounts, positions, statName, subWinStart, subWinEnd, statVals, subWinIndex, genosInSubWin, unmasked)
  File "/storage/software/diploSHIC/diploSHIC/fvTools.py", line 783, in calcAndAppendStatValForScanDiplo
    r2Matrix = allel.rogers_huff_r(genosNAlt, fill=0.0)
TypeError: rogers_huff_r() got an unexpected keyword argument 'fill'
/storage/software/python-3.6.3/miniconda3/bin/python3 /storage/software/diploSHIC/diploSHIC/makeFeatureVecsForChrArmFromVcfDiploid.py exampleApplication/ag1000g.phase1.ar3.pass.biallelic.3R.vcf.28000000-29000000.gz 3R 53200684 BFS 55000 11 exampleApplication/Anopheles-gambiae-PEST_CHROMOSOMES_AgamP3.accessible.fa.gz 0.25 0.75 exampleApplication/samples_pops.txt None exampleApplication/ag1000g.phase1.ar3.pass.biallelic.3R.vcf.28000000-29000000.gz.diploid.fvec

I wonder if this a bug? or something wrong on my side? for example an issue with my diploSHIC installation?

**Comment by yunusbb** [comment]
Solved - was fixed in a recent commit
